"""seed_data.py -- Load TheLook E-Commerce sample data into Cloud SQL Postgres.

Pulls a subset of the public BigQuery dataset `bigquery-public-data.thelook_ecommerce`
and inserts it into a Cloud SQL Postgres instance (the demo source database).

Three tables are loaded:
  orders        -- ~10k rows, full-load demo
  users         -- ~10k rows, merge (upsert) demo
  order_items   -- ~50k rows, incremental (watermark) demo

This script is intentionally standalone -- it does not import any pipeline code.
Its only job is to prepare the source database for the demo.

Usage:
  # Reads connection info from infra/.env (generated by infra/setup.sh)
  uv run python scripts/seed_data.py

  # Or pass env vars directly:
  SQL_HOST=1.2.3.4 SQL_DB=thelook SQL_USER=spark SQL_PASSWORD=pass \
  uv run python scripts/seed_data.py
"""

import logging
import os
import pathlib

import pandas as pd
import psycopg2
from google.cloud import bigquery

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s %(levelname)s: %(message)s",
)
logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

_ENV_FILE = pathlib.Path(__file__).parent.parent / "infra" / ".env"
_BQ_PUBLIC_PROJECT = "bigquery-public-data"
_BQ_DATASET = "thelook_ecommerce"
_ROW_LIMIT = 10_000


def _load_env() -> None:
    """Load infra/.env into os.environ if the file exists."""
    if not _ENV_FILE.exists():
        return
    with open(_ENV_FILE) as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            key, _, value = line.partition("=")
            os.environ.setdefault(key.strip(), value.strip())


def _get_conn_params() -> dict:
    return {
        "host": os.environ["SQL_HOST"],
        "dbname": os.environ["SQL_DB"],
        "user": os.environ["SQL_USER"],
        "password": os.environ["SQL_PASSWORD"],
        "port": int(os.environ.get("SQL_PORT", "5432")),
        "connect_timeout": 30,
    }


# ---------------------------------------------------------------------------
# BQ fetch helpers
# ---------------------------------------------------------------------------


def _fetch_from_bq(client: bigquery.Client, query: str) -> pd.DataFrame:
    """Run a BigQuery query and return results as a DataFrame."""
    logger.info("Fetching from BigQuery...")
    df = client.query(query).to_dataframe()
    logger.info("Fetched %d rows.", len(df))
    return df


# ---------------------------------------------------------------------------
# Table definitions and seed queries
# ---------------------------------------------------------------------------

# Each entry: (table_name, create_sql, bq_select_query)
_TABLES: list[tuple[str, str, str]] = [
    (
        "orders",
        """
        CREATE TABLE IF NOT EXISTS public.orders (
            order_id        BIGINT PRIMARY KEY,
            user_id         BIGINT,
            status          VARCHAR(50),
            gender          VARCHAR(10),
            created_at      TIMESTAMP,
            returned_at     TIMESTAMP,
            shipped_at      TIMESTAMP,
            delivered_at    TIMESTAMP,
            num_of_item     INTEGER
        )
        """,
        f"""
        SELECT
            order_id,
            user_id,
            status,
            gender,
            created_at,
            returned_at,
            shipped_at,
            delivered_at,
            num_of_item
        FROM `{_BQ_PUBLIC_PROJECT}.{_BQ_DATASET}.orders`
        ORDER BY created_at DESC
        LIMIT {_ROW_LIMIT}
        """,
    ),
    (
        "users",
        """
        CREATE TABLE IF NOT EXISTS public.users (
            id              BIGINT PRIMARY KEY,
            first_name      VARCHAR(100),
            last_name       VARCHAR(100),
            email           VARCHAR(255),
            age             INTEGER,
            gender          VARCHAR(10),
            state           VARCHAR(100),
            street_address  VARCHAR(255),
            postal_code     VARCHAR(20),
            city            VARCHAR(100),
            country         VARCHAR(100),
            latitude        DOUBLE PRECISION,
            longitude       DOUBLE PRECISION,
            traffic_source  VARCHAR(100),
            created_at      TIMESTAMP
        )
        """,
        f"""
        SELECT
            id,
            first_name,
            last_name,
            email,
            age,
            gender,
            state,
            street_address,
            postal_code,
            city,
            country,
            latitude,
            longitude,
            traffic_source,
            created_at
        FROM `{_BQ_PUBLIC_PROJECT}.{_BQ_DATASET}.users`
        ORDER BY created_at DESC
        LIMIT {_ROW_LIMIT}
        """,
    ),
    (
        "order_items",
        """
        CREATE TABLE IF NOT EXISTS public.order_items (
            id              BIGINT PRIMARY KEY,
            order_id        BIGINT,
            user_id         BIGINT,
            product_id      BIGINT,
            inventory_item_id BIGINT,
            status          VARCHAR(50),
            created_at      TIMESTAMP,
            shipped_at      TIMESTAMP,
            delivered_at    TIMESTAMP,
            returned_at     TIMESTAMP,
            sale_price      DOUBLE PRECISION
        )
        """,
        f"""
        SELECT
            id,
            order_id,
            user_id,
            product_id,
            inventory_item_id,
            status,
            created_at,
            shipped_at,
            delivered_at,
            returned_at,
            sale_price
        FROM `{_BQ_PUBLIC_PROJECT}.{_BQ_DATASET}.order_items`
        ORDER BY created_at DESC
        LIMIT {_ROW_LIMIT * 5}
        """,
    ),
]


# ---------------------------------------------------------------------------
# Load helper
# ---------------------------------------------------------------------------


def _load_table(
    conn: "psycopg2.connection",
    table_name: str,
    create_sql: str,
    df: pd.DataFrame,
) -> None:
    """Create table (if not exists) and bulk insert rows from a DataFrame."""
    cols = list(df.columns)
    col_list = ", ".join(cols)
    placeholders = ", ".join(["%s"] * len(cols))
    insert_sql = (
        f"INSERT INTO public.{table_name} ({col_list}) VALUES ({placeholders}) "
        f"ON CONFLICT DO NOTHING"
    )

    with conn.cursor() as cur:
        logger.info("Creating table: public.%s", table_name)
        cur.execute(create_sql)
        conn.commit()

        logger.info("Inserting %d rows into public.%s...", len(df), table_name)
        rows = [tuple(row) for row in df.itertuples(index=False, name=None)]
        cur.executemany(insert_sql, rows)
        conn.commit()
        logger.info("Inserted %d rows into public.%s.", len(rows), table_name)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


def main() -> None:
    _load_env()

    conn_params = _get_conn_params()
    bq_client = bigquery.Client()

    logger.info("Connecting to Cloud SQL at %s...", conn_params["host"])
    conn = psycopg2.connect(**conn_params)
    logger.info("Connected.")

    try:
        for table_name, create_sql, bq_query in _TABLES:
            logger.info("--- %s ---", table_name)
            df = _fetch_from_bq(bq_client, bq_query)
            # Replace NaT with None for psycopg2 compatibility
            df = df.where(pd.notnull(df), None)
            _load_table(conn, table_name, create_sql, df)
    finally:
        conn.close()
        bq_client.close()

    logger.info("Seed complete. All tables loaded into Cloud SQL.")
    logger.info(
        "Verify: psql -h %s -U %s -d %s -c '\\dt'",
        conn_params["host"],
        conn_params["user"],
        conn_params["dbname"],
    )


if __name__ == "__main__":
    main()
