"""seed_data.py -- Load TheLook E-Commerce sample data into Cloud SQL Postgres.

Pulls a referentially consistent subset from the public BigQuery dataset
`bigquery-public-data.thelook_ecommerce` and inserts it into Cloud SQL Postgres.

Strategy (maintains FK integrity for the downstream join demo):
  1. Pick a seed batch of order_items (1000 rows).
  2. Derive the exact set of order_ids and user_ids referenced by those items.
  3. Fetch only the matching orders and users rows.

This guarantees the downstream analytics.daily_revenue query (which joins all
three tables) always produces results, even with a small dataset.

Usage:
  # Reads connection info from infra/.env (generated by infra/setup.sh)
  uv run python scripts/seed_data.py

  # Or pass env vars directly:
  SQL_HOST=1.2.3.4 SQL_DB=thelook SQL_USER=spark SQL_PASSWORD=pass \
  uv run python scripts/seed_data.py
"""

import logging
import os
import pathlib

import pandas as pd
import psycopg2
import psycopg2.extras
from google.cloud import bigquery

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s %(levelname)s: %(message)s",
)
logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

_ENV_FILE = pathlib.Path(__file__).parent.parent / "infra" / ".env"
_BQ_PUBLIC_PROJECT = "bigquery-public-data"
_BQ_DATASET = "thelook_ecommerce"

# Number of seed order_items to start from. orders and users are derived
# from this set, so their counts will be <= ORDER_ITEMS_LIMIT.
_ORDER_ITEMS_LIMIT = 1_000


def _load_env() -> None:
    """Load infra/.env into os.environ if the file exists."""
    if not _ENV_FILE.exists():
        return
    with open(_ENV_FILE) as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            key, _, value = line.partition("=")
            os.environ.setdefault(key.strip(), value.strip())


def _get_conn_params() -> dict:
    return {
        "host": os.environ["SQL_HOST"],
        "dbname": os.environ["SQL_DB"],
        "user": os.environ["SQL_USER"],
        "password": os.environ["SQL_PASSWORD"],
        "port": int(os.environ.get("SQL_PORT", "5432")),
        "connect_timeout": 30,
    }


# ---------------------------------------------------------------------------
# BQ fetch helpers
# ---------------------------------------------------------------------------


def _fetch_from_bq(client: bigquery.Client, query: str) -> pd.DataFrame:
    """Run a BigQuery query and return results as a DataFrame."""
    logger.info("Fetching from BigQuery...")
    df = client.query(query).to_dataframe()
    logger.info("Fetched %d rows.", len(df))
    return df


def _ids_to_bq_array(ids: list) -> str:
    """Format a list of integer IDs as a BigQuery UNNEST-able array literal."""
    return "(" + ", ".join(str(i) for i in ids) + ")"


# ---------------------------------------------------------------------------
# Table DDL
# ---------------------------------------------------------------------------

_CREATE_ORDER_ITEMS = """
CREATE TABLE IF NOT EXISTS public.order_items (
    id                BIGINT PRIMARY KEY,
    order_id          BIGINT,
    user_id           BIGINT,
    product_id        BIGINT,
    inventory_item_id BIGINT,
    status            VARCHAR(50),
    created_at        TIMESTAMP,
    shipped_at        TIMESTAMP,
    delivered_at      TIMESTAMP,
    returned_at       TIMESTAMP,
    sale_price        DOUBLE PRECISION
)
"""

_CREATE_ORDERS = """
CREATE TABLE IF NOT EXISTS public.orders (
    order_id     BIGINT PRIMARY KEY,
    user_id      BIGINT,
    status       VARCHAR(50),
    gender       VARCHAR(10),
    created_at   TIMESTAMP,
    returned_at  TIMESTAMP,
    shipped_at   TIMESTAMP,
    delivered_at TIMESTAMP,
    num_of_item  INTEGER
)
"""

_CREATE_USERS = """
CREATE TABLE IF NOT EXISTS public.users (
    id             BIGINT PRIMARY KEY,
    first_name     VARCHAR(100),
    last_name      VARCHAR(100),
    email          VARCHAR(255),
    age            INTEGER,
    gender         VARCHAR(10),
    state          VARCHAR(100),
    street_address VARCHAR(255),
    postal_code    VARCHAR(20),
    city           VARCHAR(100),
    country        VARCHAR(100),
    latitude       DOUBLE PRECISION,
    longitude      DOUBLE PRECISION,
    traffic_source VARCHAR(100),
    created_at     TIMESTAMP
)
"""


# ---------------------------------------------------------------------------
# Load helper
# ---------------------------------------------------------------------------


def _to_python(x: object) -> object:
    """Convert numpy/pandas scalars to native Python types for psycopg2."""
    if x is None:
        return None
    try:
        if pd.isnull(x):
            return None
    except (TypeError, ValueError):
        pass
    return x.item() if hasattr(x, "item") else x


def _load_table(
    conn: "psycopg2.connection",
    table_name: str,
    create_sql: str,
    df: pd.DataFrame,
) -> None:
    """Create table (if not exists) and bulk insert rows using execute_values."""
    cols = list(df.columns)
    col_list = ", ".join(cols)
    insert_sql = (
        f"INSERT INTO public.{table_name} ({col_list}) VALUES %s ON CONFLICT DO NOTHING"
    )

    rows = [
        tuple(_to_python(x) for x in row)
        for row in df.itertuples(index=False, name=None)
    ]

    with conn.cursor() as cur:
        logger.info("Creating table: public.%s", table_name)
        cur.execute(create_sql)
        conn.commit()

        logger.info("Inserting %d rows into public.%s...", len(rows), table_name)
        psycopg2.extras.execute_values(cur, insert_sql, rows, page_size=500)
        conn.commit()
        logger.info("Inserted %d rows into public.%s.", len(rows), table_name)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


def main() -> None:
    _load_env()

    conn_params = _get_conn_params()
    bq_client = bigquery.Client()

    logger.info("Connecting to Cloud SQL at %s...", conn_params["host"])
    conn = psycopg2.connect(**conn_params)
    logger.info("Connected.")

    try:
        # Step 1: fetch seed order_items (no ORDER BY -- storage order is fine)
        logger.info("--- order_items (seed batch) ---")
        oi_df = _fetch_from_bq(
            bq_client,
            f"""
            SELECT
                id, order_id, user_id, product_id, inventory_item_id,
                status, created_at, shipped_at, delivered_at, returned_at,
                sale_price
            FROM `{_BQ_PUBLIC_PROJECT}.{_BQ_DATASET}.order_items`
            LIMIT {_ORDER_ITEMS_LIMIT}
            """,
        )

        # Step 2: derive the exact order_ids and user_ids referenced
        order_ids = oi_df["order_id"].dropna().astype(int).unique().tolist()
        user_ids = oi_df["user_id"].dropna().astype(int).unique().tolist()
        logger.info(
            "Derived %d distinct order_ids and %d distinct user_ids from order_items.",
            len(order_ids),
            len(user_ids),
        )

        # Step 3: fetch only the matching orders and users
        logger.info("--- orders (matching order_ids) ---")
        orders_df = _fetch_from_bq(
            bq_client,
            f"""
            SELECT
                order_id, user_id, status, gender,
                created_at, returned_at, shipped_at, delivered_at, num_of_item
            FROM `{_BQ_PUBLIC_PROJECT}.{_BQ_DATASET}.orders`
            WHERE order_id IN {_ids_to_bq_array(order_ids)}
            """,
        )

        logger.info("--- users (matching user_ids) ---")
        users_df = _fetch_from_bq(
            bq_client,
            f"""
            SELECT
                id, first_name, last_name, email, age, gender,
                state, street_address, postal_code, city, country,
                latitude, longitude, traffic_source, created_at
            FROM `{_BQ_PUBLIC_PROJECT}.{_BQ_DATASET}.users`
            WHERE id IN {_ids_to_bq_array(user_ids)}
            """,
        )

        # Step 4: load into Cloud SQL (orders and users first for FK sanity)
        _load_table(conn, "orders", _CREATE_ORDERS, orders_df)
        _load_table(conn, "users", _CREATE_USERS, users_df)
        _load_table(conn, "order_items", _CREATE_ORDER_ITEMS, oi_df)

    finally:
        conn.close()
        bq_client.close()

    logger.info("Seed complete.")
    logger.info(
        "order_items: %d rows, orders: %d rows, users: %d rows",
        len(oi_df),
        len(orders_df),
        len(users_df),
    )
    logger.info(
        "Verify: psql -h %s -U %s -d %s -c '\\dt'",
        conn_params["host"],
        conn_params["user"],
        conn_params["dbname"],
    )


if __name__ == "__main__":
    main()
